# This workflow will build a .NET project

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build 
    - name: Publish
      run: dotnet publish -o ${{env.DOTNET_ROOT}}/publish
    - name: Upload artifacts to GitHub Artifact Store
      uses: actions/upload-artifact@v3
      with: 
        name: my-artifacts
        path: ${{env.DOTNET_ROOT}}/publish

  deploy: 
     runs-on: self-hosted
     needs: build
     steps:
     - name: Download artifacts to VM
       uses: actions/download-artifact@v3
       with: 
         name: my-artifacts
     - name: Stop webapp
       run: sudo systemctl stop MyApp.service
     - name: Start webapp
       run: sudo systemctl start MyApp.service